# Site settings
author: Nick Walton
title: Making Changes
header-img: img/home-bg.png
email: cactar65@gmail.com
copyright_name: Nick Walton
description: > # this means to ignore newlines until "baseurl:"
  A Blog about making changes
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  cactar65

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
